### ISSUE TITLE
Does this work with heroku?

### ISSUE THREAD

**Issue by mitya777** [smrsan76/x-hexo-app-connect#1]
Would deploying a node app with attached hexo blog work with heroku?

**Comment by smrsan76** [comment]
### Hello dear @mitya777 
This plugin is mostly helpful for testing or blog (live/draft) preview usages, but if you served your public blog with hexo-server/x-hexo-app-... on the internet, it could cause to slow down your blog loading speed.
However, I wrote this plugin for all the situations.
__You can test it and report the issues here if there was a problem.__
I can't use The Heroku Services. Because I'm an Iranian developer and **Iranians have been banned and can't use The Heroku Services**.

### Thanks for reporting issue
You can always report the issues to help me improve this package 😉

**Comment by smrsan76** [comment]
### Hello dear @mitya777
This issue is opened 4 days ago, and there's no reply, yet.
I decided to close this issue. **BUT** if there was another problem about this subject,
fill free, open this issue, and help me improve this package ... tnx
